### PR TITLE
Write TAP ok line for each clean file

### LINKED ISSUE #4: Report passing files as ok
In my usage of this plugin, I've sometimes become nervous when all the lint tests pass with no output that perhaps my script is broken, a glob is incorrect due to a refactoring, etc. Basically I become concerned that either some of all of my source files are not actually being linted.

Therefore, I thought I could address this via printing a TAP `ok` message for each file that cleanly lints. This would give me assurance that all is really well, as well as if I suddenly see the number of tests decrease unexpectedly, I know maybe something is up.

I made a fork and a proof-of-concept. Here's a snippet of the output:

```
TAP version 13
not ok 1
    ---
    message:  'bingo' is defined but never used
    severity: error
    file:     /Users/plyons/projects/mjournal/app/api.js
    line:     7
    name:     no-unused-vars
    ...

not ok 1
    ---
    message:  'bango' is defined but never used
    severity: error
    file:     /Users/plyons/projects/mjournal/app/api.js
    line:     36
    name:     no-unused-vars
    ...

ok 2 clean lint: browser.js
ok 3 clean lint: cli.js
ok 4 clean lint: cli.tap.js
ok 5 clean lint: paginated.js
```

What do you think of that functionality? I can submit a PR for it if you like it, or just fork this into a totally separate package if you prefer.

### PR DESCRIPTION
**Pull request by focusaurus**
Fixes #4

### CODE REVIEW

File: tap.js [hunk 1]
```diff
@@ -1,14 +1,14 @@
 'use strict';
+var path = require('path');
 var yamlish = require('yamlish');
 
 module.exports = function (results) {
 	var ret = '\nTAP version 13\n';
 	var total = 0;
-
```
Comment (sindresorhus) [inline tap.js]: Don't do unrelated changes.

File: tap.js [hunk 2]
```diff
@@ -1,14 +1,14 @@
...
 	results.forEach(function (result) {
 		var messages = result.messages;
-
 		if (messages.length === 0) {
+			ret += 'ok ' + (++total) + ' clean lint: ' + path.basename(result.filePath) + '\n'
```
Comment (sindresorhus) [inline tap.js]: I don't see the point of `clean lint: `, it's already logging `ok`. It should use `path.relative` not the basename. You might have files with the same name in various levels of your project.

Also missing a semicolon.

**Comment by focusaurus** [comment]
OK I have made changes as per your review.
